### ISSUE TITLE
Stations order error on the route which seems to be correct

### ISSUE THREAD

**Issue by quchasz** [edk-software/edk-route-verifier#61] opened 2019-02-26 11:01 UTC
On the route 
https://my.edk.org.pl/s/WepzGGi3v1gm/routes/1982/info
verifier throws "stations order" error, while stations are ordered fine.

The beginning and the end of the route overlaps on distance ~5km, as well 1st station is located ~3km away from the beginning, what can be reason of issue.

I'm attaching kml file for reference (file extension renamed to .txt)

[edk-gps-route-1982.kml.txt](https://github.com/edk-software/edk-route-verifier/files/2907813/edk-gps-route-1982.kml.txt)

**Comment by quchasz** [comment] 2019-02-26 22:38
This issue results from the poor quality of the trace - on the part where the beginning and the ending of route overlaps the path twisted both ends very often, so it was not possible to find which one is beginning and which one is ending. In consequence (one or more, hard to say) station points was added near to wrong end of path.

When I reedited path to make it clean, and when I put statin points in near to correct end of path validation passed.

Edited kml file attached below:
[edk-gps-route-1982-route-corrected.kml.txt](https://github.com/edk-software/edk-route-verifier/files/2907830/edk-gps-route-1982-route-corrected.kml.txt)

**Comment by qooban** [comment] 2019-03-01 07:13
Duplicate of https://github.com/edk-software/edk-route-verifier/issues/46 ?

**Comment by quchasz** [comment] 2019-03-01 07:24
Yes, seems to be duplicate of issue #46 - looks like verifier checks incorrect section of path if more than one path segment runs near to the Station point.

**Comment by qooban** [comment] 2019-03-01 08:57
Closed as duplicate. Example KML will be used during implementation.

**Closed by qooban** 2019-03-01 08:57 UTC
Labels: duplicate
