### ISSUE TITLE
Route with 2 paths verified sucessfully

### ISSUE THREAD

**Issue by quchasz** [edk-software/edk-route-verifier#72] opened 2019-03-12 20:42 UTC
In the example KML attached below (trace has 2 paths - first empty and second where there are 14 Stations)
<img width="273" alt="Screen Shot 2019-03-12 at 21 40 33" src="https://user-images.githubusercontent.com/47346557/54234499-89c92e80-450f-11e9-8e21-96b257bd87eb.png">
the verifier returns error at 'only one path' test, but overall verification result is passed:
![Screen Shot 2019-03-12 at 21 33 04](https://user-images.githubusercontent.com/47346557/54234153-cf392c00-450e-11e9-8ba8-e68bce8c0905.png)

-> so the route gets approved.
===

Both paths matches each other, what seems to be a reason of problem.
[edk-gps-route-2272.kml.zip](https://github.com/edk-software/edk-route-verifier/files/2958702/edk-gps-route-2272.kml.zip)

**Comment by qooban** [comment] 2019-03-13 06:34
The problem is related to bug in v1.0.1, which was already solved.
The fix is in https://github.com/edk-software/rejony-app/pull/126 .

I still don't have access to test server, so I cannot prove that it was fix, easily. 
Can I make it invalid? I you want to wait, I'm OK.

**Comment by quchasz** [comment] 2019-03-13 07:18
Let's wait until we can confirm it got solved, either on test or on production environment.

**Comment by qooban** [comment] 2019-03-19 14:08
@quchasz Can you check on https://my.edk.org.pl ?
Looks like edk-route-verifier v1.1.4 is there right now.

**Comment by quchasz** [comment] 2019-03-22 09:33
Now it works fine - test 'single path' fails, and the route does not get approval.

Thank you!

**Closed** 2019-03-22 09:54 UTC
Labels: invalid
